#!/usr/bin/env python

import os

rootpath = '../../../../'
envGlobal = Environment(toolpath=[rootpath + 'conf/scons/site_tools'],
				        tools=['cobc', 'or32-gcc', 'buildpath', 'buildformat', 'buildsize'],
			        	ENV=os.environ)

envGlobal['BASEPATH'] = os.path.abspath('.')
envGlobal['BUILDPATH'] = os.path.abspath(rootpath + 'build/rtos/test/none_or32')

modulepath = rootpath + 'modules/'
envGlobal.SConscript([modulepath + 'utils/src/SConscript',
                      modulepath + 'time/src/SConscript',
                      modulepath + 'rtos/src/SConscript',
                      ],
                     exports='envGlobal')

env = envGlobal.Clone()

env.Append(CPPPATH=[
	'.',
	'../reference'
])
env.Append(LIBS=['cobc_rtos', 'cobc_time'])
env.Append(LIBPATH=['$BUILDPATH/lib'])

files = env.Glob('*.cpp')

program = env.Program('none_urtu', files)

envGlobal.Alias('build', program)
envGlobal.Alias('install', env.Install('bin', program))

envGlobal.Default(['build', 'install'])
