#!/usr/bin/env python

Import('envGlobal')

envGlobal.SConscript(
	[
		'utils/src/SConscript',
		'utils/ext/SConscript',
		'time/src/SConscript',
		'rtos/src/SConscript',
		'smpc/src/SConscript',
		'spp/src/SConscript',
		'pus/src/SConscript',
	],
	exports='envGlobal')