/*
 * Copyright (c) 2020-2021, German Aerospace Center (DLR)
 *
 * This file is part of the development version of OUTPOST.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Authors:
 * - 2020, Jan-Gerd Mess (DLR RY-AVS)
 * - 2021, Jan Malburg (DLR RY-AVS)
 */

#ifndef OUTPOST_SWB_TYPES_H_
#define OUTPOST_SWB_TYPES_H_

#include <outpost/utils/container/shared_buffer.h>

#include <stdint.h>

namespace outpost
{
namespace swb
{
/**
 * For detailed error handling and reporting, the following results can be generated by operations
 * within the SoftwareBus.
 * \ingroup swb
 */
enum class OperationResult : uint8_t
{
    success = 0,
    maxChannelsReached,
    noBufferAvailable,
    messageTooLong,
    sendFailed,
    noMessageAvailable,
    invalidState,
    invalidMessage,
    notFound
};

/**
 * Message is the fundamental datastructure that is passed around in the SoftwareBus.
 * \ingroup swb
 */
template <typename IDType>
struct Message
{
    IDType id;
    utils::ConstSharedBufferPointer buffer;
};

}  // namespace swb
}  // namespace outpost

#endif /* OUTPOST_SWB_TYPES_H_ */
