#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2020, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2020, Jan-Gerd Mess (DLR RY-AVS)

import os

Import('envGlobal')

envGlobal.SConscript('$EXTPATH/SConscript.gsl', exports='envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files =  env.Glob('outpost/*/*.cpp')
files += env.Glob('outpost/*/*/*.cpp')
files += env.Glob('outpost/*/*/*/*.cpp')

impl_files =  env.Glob('outpost/*/*_impl.h')
impl_files += env.Glob('outpost/*/*/*_impl.h')
impl_files += env.Glob('outpost/*/*/*/*_impl.h')


objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'swb': objects})
envGlobal.Append(sources={'swb': files})
envGlobal.Append(headers={'swb': impl_files})

library = env.StaticLibrary('outpost_swb', objects)
env.Install('$BUILDPATH/lib/', library)
