# Copyright (c) 2013, German Aerospace Center (DLR)
# All Rights Reserved.

MODULE=time

LCOV_REMOVE_PATTERN = \
	"utils/*"

all: test

include ../../conf/module.default.mk

test: test-default

coverage: coverage-default

clean: clean-default

distclean: distclean-default

.PHONY: test coverage clean
