#!/usr/bin/env pythonrtems periodic timer

import os

envGlobal = Environment(toolpath=['../../../../../conf/scons/site_tools'],
				        tools=['cobc', 'hosted', 'buildpath', 'buildformat', 'buildsize'],
				        COMPILERVERSION="4.7",
			        	ENV=os.environ)

envGlobal['BASEPATH'] = os.path.abspath('.')
envGlobal['BUILDPATH'] = os.path.abspath('../../../build/test/integration/posix_periodic_task')

rootpath = '../../../..'
envGlobal.SConscript([rootpath + '/utils/src/SConscript',
                      rootpath + '/time/src/SConscript',
                      rootpath + '/rtos/src/SConscript',
                      ],
                     exports='envGlobal')

env = envGlobal.Clone()

env.Append(CPPPATH=[
	'.'
])
env.Append(LIBS=['cobc_rtos', 'cobc_time'])
env.Append(LIBPATH=['$BUILDPATH/lib'])

files  = env.Glob('*.cpp')

program = env.Program('posix_periodic_task', files)

envGlobal.Alias('build', program)
envGlobal.Alias('install', env.Install('bin', program))

envGlobal.Default(['build', 'install'])
