#!/usr/bin/tclsh

# Defines the rules that should be executed
set rules {
	F001

	L001
	L003
	L004
	L005
	L006

	T001
	T002
	T003
	T004
	T005
	T006
	T007
	T008
	T009
	T010
	T013
	T015
	T016
	T017
	T018
	T019
}

# T011 -> closing curly bracket not in the same line or column
# TODO extend to allow for other styles

# T012 -> negation operator used in its short form
