#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013-2015, 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2013-2014, 2017, Fabian Greif (DLR RY-AVS)
# - 2015, Norbert Toth (DLR RY-AVS)

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.') ])

env = envGlobal.Clone()

files  = env.Glob('unittest/*.cpp')
files += env.Glob('unittest/*/*.cpp')
files += env.Glob('unittest/*/*/*.cpp')
files += env.Glob('unittest/*/*/*/*.cpp')

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects_unittest=objects)
