#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])
envGlobal.Append(CPPPATH=[os.path.abspath('../ext/lua-5.2.3/src')])
env = envGlobal.Clone()

files  = env.Glob('*/*.cpp')
files += env.Glob('*/*/*.cpp')

env.Append(CPPPATH=['../module'])

files += ['../module/l3test/channel.cpp']

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'pus': objects})

library = env.StaticLibrary('l3test', objects)
envGlobal.Install('$BUILDPATH/lib', library)
