#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files  = env.Glob('cobc/smpc/*.cpp')
files += env.Glob('cobc/smpc/*/*.cpp')

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'smpc': objects})

library = env.StaticLibrary('cobc_smpc', objects)
envGlobal.Install('$BUILDPATH/lib', library)

