#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files  = env.Glob('cobc/smpc/*.cpp')
files += env.Glob('cobc/smpc/*/*.cpp')

library = env.StaticLibrary('cobc_smpc', files)
envGlobal.Install('$BUILDPATH/lib', library)

