#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files = env.Glob('cobc/*/*.cpp')

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'time': objects})

library = env.StaticLibrary('cobc_time', objects)
envGlobal.Install('$BUILDPATH/lib', library)

