#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files = env.Glob('cobc/time/*.cpp')

library = env.StaticLibrary('cobc_time', files)
envGlobal.Install('$BUILDPATH/lib', library)

