
ROOTFOLDER = ../../../../../ry-avs/doc

# name of the reStructuredText file, without extension (.rst)
MAINFILE    = content

# temporary build folder, path is relativ to the ROOTFOLDER
BUILDFOLDER = 0001_packet_unit_testing

# output file, path is relativ to this makefile 
RESULT      = "document/COBC-AVS-SW-TN-0001_Packet_based_Unit_Testing.pdf"

#
CONFIGURATION_FOLDER = $(ROOTFOLDER)/configuration/document_rst

include $(CONFIGURATION_FOLDER)/makefile.rst.mk

