# Copyright (c) 2014-2015, 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2014-2015, 2017, Fabian Greif (DLR RY-AVS)

ROOTFOLDER = ../../../../../ry-avs/doc

# name of the reStructuredText file, without extension (.rst)
MAINFILE    = content

# temporary build folder, path is relativ to the ROOTFOLDER
BUILDFOLDER = 0001_packet_unit_testing

# output file, path is relativ to this makefile 
RESULT      = "document/COBC-AVS-SW-TN-0001_Packet_based_Unit_Testing.pdf"

#
CONFIGURATION_FOLDER = $(ROOTFOLDER)/configuration/document_rst

include $(CONFIGURATION_FOLDER)/makefile.rst.mk

