#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[
	os.path.abspath('gmock-1.6.0/fused-src')
])

env = envGlobal.Clone()

env['CXXFLAGS_std'] = ['-std=c++98']
env['CCFLAGS_warning'] = [
	'-W',
	'-Wall',
	'-Wextra',
	'-Wformat',
	'-Wno-unused-parameter',
	'-Winit-self',
	'-Wcast-qual',
	'-Wcast-align',
	'-Wimplicit',
#	'-Wshadow',
	'-Wpointer-arith',
	'-Wwrite-strings',
	'-Wredundant-decls',
	'-Wunused',
	'-Wuninitialized',
#	'-Wconversion',
#	'-Wold-style-cast',
#	'-Wundef',
#	'-Winline',
#	'-Wmissing-declarations',
]

env.Append(LIBS=['pthread'])
env.Append(LIBPATH=['/usr/lib'])

files = env.Glob('gmock-1.6.0/fused-src/*.cc')
library = env.StaticLibrary('gmock', files)

envGlobal.Install('$BUILDPATH/lib', library)

