#!/usr/bin/env python

import os

vars = Variables('custom.py')
vars.Add(BoolVariable('coverage', 'Set to build for coverage analysis', 0))

module = 'utils'

rootpath = '../../../'
envGlobal = Environment(toolpath=[os.path.join(rootpath, '../scons-tools/site_tools')],
                        buildroot=[rootpath + 'build/'],
                        tools=['utils_buildformat'],
                        variables=vars,
                        BASEPATH=os.path.abspath('.'),
                        ENV=os.environ)
Help(vars.GenerateHelpText(envGlobal))

buildfolder = os.path.join(rootpath, 'build')
if envGlobal['coverage']:
    envGlobal.Tool('compiler_hosted_gcc_coverage')
    envGlobal.Tool('settings_buildpath')
    envGlobal['BUILDPATH'] = os.path.abspath(os.path.join(buildfolder, module, 'test/coverage'))
else:
    envGlobal.Tool('compiler_hosted_llvm')
    envGlobal.Tool('settings_buildpath')
    envGlobal['BUILDPATH'] = os.path.abspath(os.path.join(buildfolder, module, 'test/unittest'))

envGlobal.Append(CPPPATH=[
    os.path.join(rootpath, 'modules/spp/default'),
    os.path.join(rootpath, 'modules/pus/default'),
    os.path.join(rootpath, 'modules/log/default'),
])

envGlobal.SConscript(os.path.join(rootpath, 'modules/SConscript.library'), exports='envGlobal')

# The tests use C++11
envGlobal['CXXFLAGS_language'] = ['-std=c++0x']
envGlobal.SConscript(os.path.join(rootpath, 'modules/SConscript.test'), exports='envGlobal')

env = envGlobal.Clone()

env.AppendUnique(LIBS=[
    'outpost_utils',
])

files  = env.Glob('*.cpp')
files += env.Glob('outpost/*.cpp')
files += env.Glob('outpost/*/*.cpp')
files += env.Glob('outpost/*/*/*.cpp')

# Do not include the module files as library but directly as compiled objects.
# Otherwise only the realy used symbols are pulled in which yields wrong
# results for the coverage analysis.
files += env['objects'][module]

envGlobal.Alias('build', env.Program('runner', files))
envGlobal.Default('build')
