#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files  = env.Glob('unittest/*.cpp')
files += env.Glob('unittest/*/*.cpp')
files += env.Glob('unittest/*/*/*.cpp')

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'unittest': objects})
