
env = Environment()

env.Append(CPPPATH=['src', 'test', 'ext', 'ext/lua'])
env.Append(CCFLAGS=['-O2'])

envTest = env.Clone()
env.Append(CXXFLAGS=['-std=c++03'])

filesLib  = env.Glob('src/*.cpp')
filesLib += env.Glob('src/*/*.cpp')
filesLib += env.Glob('src/*/*/*.cpp')
filesLib += env.Glob('src/*/*/*/*.cpp')

objectsLib = env.Object(filesLib)

env = envTest
env.Append(CPPDEFINES={'LUA_USE_LINUX':None})
env.Append(CXXFLAGS=['-std=c++11'])

filesTest  = env.Glob('test/*.cpp')
filesTest += env.Glob('test/*/*.cpp')
filesTest += env.Glob('test/*/*/*.cpp')
filesTest += env.Glob('test/*/*/*/*.cpp')

filesTest += env.Glob('ext/*.cc')
filesTest += env.Glob('ext/*/*.c')

env.Append(LIBS=['pthread', 'rt', 'dl'])
env.Append(LINKFLAGS=['-Wl,--export-dynamic'])

program = env.Program('runner', filesTest + objectsLib)

env.Default([program])

