#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files = []
files += env.Glob('outpost/hal/*.cpp')

objects = []
for file in files:
    objects.append(env.Object(file))
envGlobal.Append(objects={'hal': objects})

library = env.StaticLibrary('outpost_hal', objects)
envGlobal.Install('$BUILDPATH/lib', library)

