#!/usr/bin/env python

import os

rootpath = '../../../../'
envGlobal = Environment(toolpath=[rootpath + 'conf/scons/site_tools'],
				        tools=['compiler/or32_aac_elf_gcc', 'utils/buildpath', 'utils/buildformat', 'utils/buildsize'],
			        	ENV=os.environ)

envGlobal['BASEPATH'] = os.path.abspath('.')
envGlobal['BUILDPATH'] = os.path.abspath(rootpath + 'build/rtos/test/none_or32')

envGlobal.Append(CPPPATH=[
    os.path.abspath(os.path.join(rootpath, 'modules/spp/default')),
    os.path.abspath(os.path.join(rootpath, 'modules/pus/default')),
    os.path.abspath(os.path.join(rootpath, 'modules/log/default')),
])

envGlobal.SConscript(os.path.join(rootpath, 'modules/SConscript.library'), exports='envGlobal')

env = envGlobal.Clone()

env.Append(CPPPATH=[
	'.',
	'../reference'
])

env.AppendUnique(LIBS=[
    'cobc_log',
    'cobc_pus',
    'cobc_spp',
    'cobc_rtos',
    'cobc_smpc',
    'cobc_time',
    'cobc_utils',
])
env.Append(LIBPATH=['$BUILDPATH/lib'])

files  = env.Glob('*.cpp')
files += env.Glob('../reference/*.cpp')

program = env.Program('none_urtu', files)

envGlobal.Alias('build', program)
envGlobal.Alias('install', env.Install('bin', program))

envGlobal.Default(['build', 'install'])
