#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014-2015, 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2014-2015, 2017, Fabian Greif (DLR RY-AVS)

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])
envGlobal.Append(CPPPATH=[os.path.abspath('../lua')])
envGlobal.Append(CPPPATH=[os.path.abspath('../ext/lua-5.3.4/src')])
env = envGlobal.Clone()

# Binding code between Lua (written in C) and C++ has to use some C casts
env.RemoveFromList('CXXFLAGS_warning', ['-Wold-style-cast'])

files = env.Glob('*/*.cpp')
files += env.Glob('*/*/*.cpp')
files += env.Glob('*/*/*/*.cpp')
files += env.Glob('../lua/modules/l3test/*.cpp')

env.Append(CPPPATH=['.'])

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'l3test': objects})

library = env.StaticLibrary('outpost_l3test', objects)
envGlobal.Install('$BUILDPATH/lib', library)
