# Copyright (c) 2020, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2020, Jan-Gerd Mess (DLR RY-AVS)

MODULE=compression

LCOV_REMOVE_PATTERN = 

all: test

include ../module.default.mk

test: test-default

test-verbose: test-verbose-default

coverage: coverage-default

clean: clean-default

distclean: distclean-default

.PHONY: test coverage clean
