#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files = env.Glob('outpost/utils/*.cpp')

objects = []
for file in files:
	objects.append(env.Object(file))
envGlobal.Append(objects={'utils': objects})

library = env.StaticLibrary('outpost_utils', objects)
envGlobal.Install('$BUILDPATH/lib', library)

