#!/usr/bin/env python

import os

Import('envGlobal')

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files = env.Glob('copc/utils/*.cpp')

library = env.StaticLibrary('cobc_utils', files)
envGlobal.Install('$BUILDPATH/lib', library)

