#!/usr/bin/env python

import os

envGlobal = Environment(toolpath=['../../../../../conf/scons/site_tools'],
				        tools=['leon3-rtems', 'buildpath', 'buildformat'],
			        	ENV=os.environ)

envGlobal['BASEPATH'] = os.path.abspath('.')
envGlobal['BUILDPATH'] = os.path.abspath('../../build/test/integration/rtems')

rootpath = '../../../..'
envGlobal.SConscript([rootpath + '/utils/src/SConscript',
                      rootpath + '/time/src/SConscript',
                      '../../../src/SConscript'],
                     exports='envGlobal')

env = envGlobal.Clone()

env.Append(CPPPATH=[
	'.'
])
env.Append(LIBS=['cobc_rtos', 'cobc_time'])
env.Append(LIBPATH=['$BUILDPATH/lib'])

files  = env.Glob('*.c')

envGlobal.Alias('build', env.Program('test-rtems', files))

